### ISSUE TITLE
Animated iPhone Gif in your great presentation

### ISSUE THREAD

**Issue by ghost** [davideast/firebase-intro#1]
@davideast I firstly wish to apologise for adding this as an issue but wanted to contact you directly about your great presentation that I am using to learn about Firebase. What tool did you use to create the animated gif of the iPhone in `gdocs4.gif`with the animated keyboard?

**Comment by davideast** [comment]
Hi @michellesp! Sorry I'm now just seeing this. I use a tool called Licecap to capture animated GIFs and a tool called Reflector to cast the phone to the screen.
